#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/sbin/sniffer


start_service() {
	host=`uci get sniffer.main.host`
	port=`uci get sniffer.main.port`
	if [ -z "${host}" ];then
	       return 
	fi

	if [ $port -lt 1 -o $port -gt 65535 ];then
 		return 		
	fi

	procd_open_instance
	procd_set_param command "$PROG" $host $port
	procd_set_param respawn 0
	procd_close_instance
}

